### ISSUE TITLE
Re-style API documentation

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry.tech#118]
After daemon team re-does what information is provided.

**Comment by eukreign** [comment]
@kauffj The approach of generating markdown and then converting that to HTML limits how much control we have in making the API look good. Since the markdown is generated and never meant to be edited by a human there isn't much advantage to having this intermediate step at all. After discussing this with @NetOperatorWibby we decided it would be simpler and produce a higher quality document if I generated HTML directly in the `gen_docs.py` script.

**Comment by NetOperatorWibby** [comment]
Closed via https://github.com/lbryio/lbry.tech/commit/68a1e27881dbca38b5a28bc8774fb3936f688b91
