### ISSUE TITLE
Email Signup UX

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry.tech#170]
- [x] The regexp is incorrect and fails valid emails (e.g. `jeremy+test@lbry.io`). Since we're already validating server-side, client side validation adds basically no value. If you want client-side validation for UX purposes, then just check for the `@` symbol or use an extremely generous regexp.
- [x] Submit on enter (alternatively, make it a real form)
- [x] No feedback on invalid email or failure (no feedback it's working while submitted, either)
- [ ] JavaScript should be more tightly/obviously coupled with markup

**Comment by NetOperatorWibby** [comment]
Your first point is interesting because that regex works with my personal projects and using that specific use case. Also, the regex works on https://regexr.com.

I dislike forms because I don't like dealing with ajax and/or whatever forms need to send things. The rest of what you suggested are simple changes.
