### ISSUE TITLE
Header Hierarchy / SEO

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry.tech#92]
My knowledge of header tags and SEO is at least 5 years old, so if this ticket seems based on incorrect assumptions, let me know.

- The homepage is missing an `h1`
- Most pages are missing an `h1`. The element that serves as a page header is currently an `h2` (presumably it should be an `h1`?).
- If the page title is rendered as an `h1`, then `h1`s should presumably not be allowed in page markdown.

**Comment by Invariant-Change** [comment]
Yes, this is partially correct.

## Page Structure

Page structure, such as having all the usual **components** for a page such as `H1`, `H2` etc is still very important for various reasons. Not only does it make a website look more professional, but also for accessibility for the below reasons..

There is debate over if `H1`'s are needed anymore or if you can have multiple one. And the answer is both yes and no.

While technically you can have multiple `H1`'s in certain circumstances, it's not recommended and the there are combining factors that can damage SEO if trying to use new methods. Likewise, omitting `H1`'s from a webpage can have a negative impact on SEO and accessibility.

## H1, SEO and Accessibility

The `H1` is still a good place to put your **keywords**, not so much because it's in an H1 as that's not really a formula anymore, but because the `H1` usually at the **top** of the page and keywords at the top are considered more important than keywords below them. Also, other search engines still use `H1`'s to prioritise keywords. 

And all pages that contain text should have an `H1` for good grammar.

Google standards are paving the way to use multiple `H1` within a document if the document is split into unique `<sections>`.

![image](https://user-images.githubusercontent.com/29914179/41267810-607932ec-6e40-11e8-96ab-fee789ea07e1.png)

This allows for a page to contain multiple `<articles>` each with their own `H1` when correctly formatted to support such a system.

```
<article>
<section>
<h1></h1>
<p></p>
</section>
</article>
<article>
<section>
<h1></h1>
<p></p>
</section>
</article>
```
However, this **isn't** fully implemented yet and if a page uses multiple `H1`'s that are incorrectly nested, not only can it damage **SEO** via bad grammar **algorithms**, but may also break devices used for **accessibility** such as **screen readers** for the visually impaired; which could also be another factor **harming** SEO.

The **recommended** "*best practice*" is to stick to the current system, making sure sites remain **accessible** for people with **disabilities** with good grammar using **title tags** correctly **nested** in their logical order with only one `H1` per page.
